server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: yy
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化大小、最小、最大连接数
      initial-size: 1
      min-idle: 1
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 监控后台账号和密码
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      filter:
        # 配置 StatFilter
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
      filters: stat, wall, config, log4j2
      pool-prepared-statements: true
      web-stat-filter:
        enabled: true
        session-stat-enable: true
        exclusions: /*.js,/*.gif,/*.jpg,/*.bmp,/*.png,/*.css,/*.ico,/druid/*
        url-pattern: /*
      aop-patterns: com.yy.springbootmybatis.*